---
title: "Personal Project"
author: "Tim Pendry"
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
ggplot2::ggplot()
library(plotly)
```

```{r unions}
union <-read_csv("Union csv.csv")
Year<-as.Date("Year", "%Y")

```
```{r}
graph <- ggplot(data = union, aes(x = Year))+
  geom_line(aes(y = All), color = "navy", size = 2)+
  geom_line(aes(y = midsixty), color = "tan", size = 2)+
  geom_line(aes(y=fivepercent), color = "darkred", size = 2)+labs(title = "Union Membership & Income Inequality")+labs(x = "Year")+labs(y = "Percent")

ggplotly(graph)
```


```{r}
linear60 <-lm(midsixty ~ All, union)
summary(linear60)
linearall <-lm(fivepercent ~ All, union)
summary(linearall)

linearpriv <-lm(midsixty ~ priv, union)
summary(linearpriv)

linearpriv <-lm(fivepercent ~ priv, union)
summary(linearpriv)

linearpub <-lm(midsixty ~ pub, union)
summary(linearpub)

linearpriv <-lm(fivepercent ~ pub, union)
summary(linearpub)
```


